# Generated by Django 5.2.8 on 2025-12-10 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droguerias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drogueria',
            name='horarios',
            field=models.TextField(blank=True, help_text='Ej: Lunes-Viernes 9AM-6PM', null=True),
        ),
        migrations.AlterField(
            model_name='drogueria',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='droguerias_propias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('drogueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='droguerias.drogueria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_droguerias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizada'],
                'unique_together': {('drogueria', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente_tipo', models.CharField(choices=[('usuario', 'Usuario'), ('drogueria', 'Droguería')], max_length=20)),
                ('remitente_id', models.IntegerField(blank=True, help_text='ID del usuario o droguería que envía', null=True)),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='droguerias.conversacion')),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
    ]
