# Generated by Django 5.2.8 on 2025-12-11 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droguerias', '0002_drogueria_horarios_alter_drogueria_propietario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDrogueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('propietario', 'Propietario'), ('manager', 'Manager'), ('empleado', 'Empleado')], default='empleado', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('drogueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_membresia', to='droguerias.drogueria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droguerias_membresia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía Usuario-Droguería',
                'verbose_name_plural': 'Membresías Usuario-Droguería',
                'unique_together': {('usuario', 'drogueria')},
            },
        ),
    ]
