# Generated by Django 5.2.8 on 2025-12-11 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droguerias', '0003_usuariodrogueria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioDrogueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_inventario', models.DecimalField(decimal_places=2, default=0, help_text='Valor total en costo de compra', max_digits=15)),
                ('valor_venta_total', models.DecimalField(decimal_places=2, default=0, help_text='Valor total en precio de venta', max_digits=15)),
                ('cantidad_medicamentos', models.PositiveIntegerField(default=0, help_text='Total de medicamentos únicos')),
                ('cantidad_stock_total', models.PositiveIntegerField(default=0, help_text='Total de unidades en stock')),
                ('ultimo_movimiento', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('drogueria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='droguerias.drogueria')),
            ],
            options={
                'verbose_name': 'Inventario Droguería',
                'verbose_name_plural': 'Inventarios Droguería',
            },
        ),
        migrations.CreateModel(
            name='MovimientoDrogueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_nombre', models.CharField(help_text='Nombre del medicamento movido', max_length=200)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada de compra'), ('salida', 'Salida/Venta'), ('ajuste', 'Ajuste de inventario'), ('transferencia_out', 'Transferencia enviada'), ('transferencia_in', 'Transferencia recibida'), ('devolución', 'Devolución')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='cantidad × precio_unitario', max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('drogueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='droguerias.drogueria')),
                ('drogueria_destino', models.ForeignKey(blank=True, help_text='Droguería destino si es transferencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_recibidos', to='droguerias.drogueria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Droguería',
                'verbose_name_plural': 'Movimientos de Droguería',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['drogueria', '-creado'], name='droguerias__droguer_d286a7_idx'), models.Index(fields=['tipo_movimiento'], name='droguerias__tipo_mo_deaec8_idx')],
            },
        ),
    ]
