# Generated by Django 5.2.8 on 2025-11-28 19:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_add_indexes'),
        ('pedidos', '0003_pedido_descuento_pedido_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.medicamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
