# Generated by Django 5.2.8 on 2025-12-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
        ('pedidos', '0005_historialpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='pedidos.pedido'),
        ),
    ]
