# Generated by Django 5.2.8 on 2025-12-07 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('droguerias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reporte', models.CharField(help_text='Código único identificador del reporte', max_length=50, unique=True, verbose_name='ID del Reporte')),
                ('titulo', models.CharField(help_text='Título descriptivo del reporte', max_length=200, verbose_name='Título del Reporte')),
                ('tipo_reporte', models.CharField(choices=[('inventario', 'Inventario'), ('ventas', 'Ventas'), ('financiero', 'Financiero'), ('medicamentos', 'Medicamentos'), ('pedidos', 'Pedidos'), ('clientes', 'Clientes'), ('general', 'General'), ('personalizado', 'Personalizado')], default='general', help_text='Clasificación del tipo de reporte', max_length=50, verbose_name='Tipo de Reporte')),
                ('fecha_medicion', models.DateTimeField(help_text='Fecha y hora en que se realizó la medición o se tomaron los datos', verbose_name='Fecha de Medición')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual del reporte', max_length=20, verbose_name='Estado del Reporte')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del contenido del reporte', null=True, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones, notas o comentarios adicionales', null=True, verbose_name='Observaciones')),
                ('datos_json', models.JSONField(blank=True, default=dict, help_text='Datos estructurados del reporte en formato JSON', verbose_name='Datos JSON')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el reporte', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Actualización')),
                ('fecha_revision', models.DateTimeField(blank=True, help_text='Fecha y hora en que fue revisado el reporte', null=True, verbose_name='Fecha de Revisión')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que fue aprobado el reporte', null=True, verbose_name='Fecha de Aprobación')),
                ('archivo_pdf', models.CharField(blank=True, help_text='Ruta al archivo PDF generado del reporte', max_length=500, null=True, verbose_name='Archivo PDF')),
                ('pdf_generado', models.BooleanField(default=False, help_text='Indica si el PDF del reporte ya fue generado', verbose_name='PDF Generado')),
                ('correo_enviado', models.BooleanField(default=False, help_text='Indica si el reporte fue enviado por correo electrónico', verbose_name='Correo Enviado')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('drogueria', models.ForeignKey(blank=True, help_text='Droguería asociada al reporte (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='droguerias.drogueria', verbose_name='Droguería')),
                ('revisado_por', models.ForeignKey(blank=True, help_text='Usuario que revisó este reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['id_reporte'], name='rep_id_reporte_idx'), models.Index(fields=['estado'], name='rep_estado_idx'), models.Index(fields=['fecha_medicion'], name='rep_fecha_medicion_idx'), models.Index(fields=['tipo_reporte'], name='rep_tipo_reporte_idx'), models.Index(fields=['creado_por', 'fecha_creacion'], name='rep_creado_por_idx')],
            },
        ),
    ]
